CREATE TABLE IF NOT EXISTS users
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    password character varying(255) COLLATE pg_catalog."default" NOT NULL,
    username character varying(255) COLLATE pg_catalog."default" NOT NULL,
    name character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_username_key UNIQUE (username)
    );


CREATE TABLE IF NOT EXISTS user_roles
(
    user_id bigint NOT NULL,
    role character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT fkhfh9dx7w3ubf1co1vdev94g3f FOREIGN KEY (user_id)
    REFERENCES users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    );

CREATE TABLE IF NOT EXISTS vehicles
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    vehicle_license_number character varying(255) COLLATE pg_catalog."default",
    vehicle_manufacturer character varying(255) COLLATE pg_catalog."default",
    vehicle_model character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT vehicles_pkey PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS vehicle_bookings
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    booking_confirmed_time timestamp(6) without time zone,
    booking_end_time timestamp(6) without time zone,
    booking_request_time timestamp(6) without time zone,
    booking_start_time timestamp(6) without time zone,
    confirmed boolean NOT NULL,
    driver_id bigint,
    passenger_id bigint,
    vehicle_id bigint,
    CONSTRAINT vehicle_bookings_pkey PRIMARY KEY (id),
    CONSTRAINT fkhyuh3mi5jiunaxpu78esj504w FOREIGN KEY (vehicle_id)
    REFERENCES vehicles (id) MATCH SIMPLE
                                        ON UPDATE NO ACTION
                                        ON DELETE NO ACTION,
    CONSTRAINT fkj3536yfpfm5reopxur2fraqei FOREIGN KEY (passenger_id)
    REFERENCES users (id) MATCH SIMPLE
                                        ON UPDATE NO ACTION
                                        ON DELETE NO ACTION,
    CONSTRAINT fkspg4030du5h45pncahtsjigln FOREIGN KEY (driver_id)
    REFERENCES users (id) MATCH SIMPLE
                                        ON UPDATE NO ACTION
                                        ON DELETE NO ACTION
    );
